<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>cvnet.ico</ApplicationIcon>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="cvnet.ico" />
    <None Remove="Fonts\NotoSansJP-Black.ttf" />
    <None Remove="Fonts\NotoSansJP-Bold.ttf" />
    <None Remove="Fonts\NotoSansJP-ExtraBold.ttf" />
    <None Remove="Fonts\NotoSansJP-ExtraLight.ttf" />
    <None Remove="Fonts\NotoSansJP-Light.ttf" />
    <None Remove="Fonts\NotoSansJP-Medium.ttf" />
    <None Remove="Fonts\NotoSansJP-Regular.ttf" />
    <None Remove="Fonts\NotoSansJP-SemiBold.ttf" />
    <None Remove="Fonts\NotoSansJP-Thin.ttf" />
    <None Remove="Images\button_icon\add_icon.png" />
    <None Remove="Images\button_icon\back_icon.png" />
    <None Remove="Images\button_icon\calendar_icon.png" />
    <None Remove="Images\button_icon\clear_button.png" />
    <None Remove="Images\button_icon\delete_icon.png" />
    <None Remove="Images\button_icon\enter_icon.png" />
    <None Remove="Images\button_icon\json_icon.png" />
    <None Remove="Images\button_icon\next_icon.png" />
    <None Remove="Images\button_icon\printer_icon.png" />
    <None Remove="Images\button_icon\refresh_icon.png" />
    <None Remove="Images\button_icon\search_icon.png" />
    <None Remove="Images\button_icon\update_icon.png" />
    <None Remove="Images\mainmenu_icon\Allocation.png" />
    <None Remove="Images\mainmenu_icon\Budget.png" />
    <None Remove="Images\mainmenu_icon\Calendar.png" />
    <None Remove="Images\mainmenu_icon\CPA.png" />
    <None Remove="Images\mainmenu_icon\CVPOS.png" />
    <None Remove="Images\mainmenu_icon\HHT.png" />
    <None Remove="Images\mainmenu_icon\Home.png" />
    <None Remove="Images\mainmenu_icon\Logistics.png" />
    <None Remove="Images\mainmenu_icon\LoyalCustomer.png" />
    <None Remove="Images\mainmenu_icon\Management.png" />
    <None Remove="Images\mainmenu_icon\Master.png" />
    <None Remove="Images\mainmenu_icon\MasterHojo.png" />
    <None Remove="Images\mainmenu_icon\MoneyManagement.png" />
    <None Remove="Images\mainmenu_icon\Monthly.png" />
    <None Remove="Images\mainmenu_icon\Noti.png" />
    <None Remove="Images\mainmenu_icon\OrderBy.png" />
    <None Remove="Images\mainmenu_icon\OrderFrom.png" />
    <None Remove="Images\mainmenu_icon\Sales.png" />
    <None Remove="Images\mainmenu_icon\SalesAnalysis1.png" />
    <None Remove="Images\mainmenu_icon\SalesAnalysis2.png" />
    <None Remove="Images\mainmenu_icon\Settings.png" />
    <None Remove="Images\mainmenu_icon\Shipping.png" />
    <None Remove="Images\mainmenu_icon\Shop.png" />
    <None Remove="Images\mainmenu_icon\StockManagement.png" />
    <None Remove="Images\mainmenu_icon\StockTaking.png" />
    <None Remove="Images\mainmenu_icon\Supply.png" />
    <None Remove="Images\mainmenu_icon\TimeNavi.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="cvnet.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\NotoSansJP-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3240.44" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="MvvmLightLibs" Version="5.4.1.1" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CvnetBaseCore">
      <HintPath>..\CvnetBaseCore\bin\Debug\net9.0\CvnetBaseCore.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="cvnet.ico" />
    <Resource Include="Fonts\NotoSansJP-Black.ttf" />
    <Resource Include="Fonts\NotoSansJP-Bold.ttf" />
    <Resource Include="Fonts\NotoSansJP-ExtraBold.ttf" />
    <Resource Include="Fonts\NotoSansJP-ExtraLight.ttf" />
    <Resource Include="Fonts\NotoSansJP-Light.ttf" />
    <Resource Include="Fonts\NotoSansJP-Medium.ttf" />
    <Resource Include="Fonts\NotoSansJP-Regular.ttf" />
    <Resource Include="Fonts\NotoSansJP-Thin.ttf" />
    <Resource Include="Images\button_icon\add_icon.png" />
    <Resource Include="Images\button_icon\back_icon.png" />
    <Resource Include="Images\button_icon\calendar_icon.png" />
    <Resource Include="Images\button_icon\clear_button.png" />
    <Resource Include="Images\button_icon\delete_icon.png" />
    <Resource Include="Images\button_icon\enter_icon.png" />
    <Resource Include="Images\button_icon\json_icon.png" />
    <Resource Include="Images\button_icon\next_icon.png" />
    <Resource Include="Images\button_icon\printer_icon.png" />
    <Resource Include="Images\button_icon\refresh_icon.png" />
    <Resource Include="Images\button_icon\search_icon.png" />
    <Resource Include="Images\button_icon\update_icon.png" />
    <Resource Include="Images\mainmenu_icon\Allocation.png" />
    <Resource Include="Images\mainmenu_icon\Budget.png" />
    <Resource Include="Images\mainmenu_icon\Calendar.png" />
    <Resource Include="Images\mainmenu_icon\CPA.png" />
    <Resource Include="Images\mainmenu_icon\CVPOS.png" />
    <Resource Include="Images\mainmenu_icon\HHT.png" />
    <Resource Include="Images\mainmenu_icon\Home.png" />
    <Resource Include="Images\mainmenu_icon\Logistics.png" />
    <Resource Include="Images\mainmenu_icon\LoyalCustomer.png" />
    <Resource Include="Images\mainmenu_icon\Management.png" />
    <Resource Include="Images\mainmenu_icon\Master.png" />
    <Resource Include="Images\mainmenu_icon\MasterHojo.png" />
    <Resource Include="Images\mainmenu_icon\MoneyManagement.png" />
    <Resource Include="Images\mainmenu_icon\Monthly.png" />
    <Resource Include="Images\mainmenu_icon\Noti.png" />
    <Resource Include="Images\mainmenu_icon\OrderBy.png" />
    <Resource Include="Images\mainmenu_icon\OrderFrom.png" />
    <Resource Include="Images\mainmenu_icon\Sales.png" />
    <Resource Include="Images\mainmenu_icon\SalesAnalysis1.png" />
    <Resource Include="Images\mainmenu_icon\SalesAnalysis2.png" />
    <Resource Include="Images\mainmenu_icon\Settings.png" />
    <Resource Include="Images\mainmenu_icon\Shipping.png" />
    <Resource Include="Images\mainmenu_icon\Shop.png" />
    <Resource Include="Images\mainmenu_icon\StockManagement.png" />
    <Resource Include="Images\mainmenu_icon\StockTaking.png" />
    <Resource Include="Images\mainmenu_icon\Supply.png" />
    <Resource Include="Images\mainmenu_icon\TimeNavi.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views.Common\WebTextView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Debug.json">
      <DependentUpon>appsettings.json</DependentUpon>
      <SubType>Designer</SubType>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Release.json">
      <DependentUpon>appsettings.json</DependentUpon>
      <SubType>Designer</SubType>
    </None>
    <None Update="Nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="set projdir=$(ProjectDir)&#xD;&#xA;set projcfg=$(Configuration)&#xD;&#xA;set projout=$(OutDir)&#xD;&#xA;call app-post-build.bat&#xD;&#xA;" />
  </Target>
</Project>
